//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHocSinhHVT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOCPHI
    {
        public string MaHocPhi { get; set; }
        public string MaNH { get; set; }
        public string MaHS { get; set; }
        public int DONGIA { get; set; }
        public System.DateTime NgayThongBao { get; set; }
    
        public virtual HOCSINH HOCSINH { get; set; }
        public virtual NAMHOC NAMHOC { get; set; }
    }
}
