//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class HOCPHI
    {
        [DisplayName("Học phí")]
        public string MaHocPhi { get; set; }
        [DisplayName("Năm học")]
        public string MaNH { get; set; }
        [DisplayName("Học sinh")]
        public string MaHS { get; set; }
        [DisplayName("Đơn giá")]
        public int DONGIA { get; set; }
        [DisplayName("Ngày thông báo")]
        public System.DateTime NgayThongBao { get; set; }
        [DisplayName("Loại học phí")]
        public string MaLHP { get; set; }
        [DisplayName("Ngày đóng tiền")]
        public Nullable<System.DateTime> NgayDongTien { get; set; }
    
        public virtual HOCSINH HOCSINH { get; set; }
        public virtual NAMHOC NAMHOC { get; set; }
        public virtual LOAIHOCPHI LOAIHOCPHI { get; set; }
    }
}
