//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOCSINH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOCSINH()
        {
            this.CTHPs = new HashSet<CTHP>();
            this.HOCPHIs = new HashSet<HOCPHI>();
        }
    
        public string MaHS { get; set; }
        public string HoHS { get; set; }
        public string TenHS { get; set; }
        public string AnhHS { get; set; }
        public bool GioiTinh { get; set; }
        public string MaLop { get; set; }
        public string MaPH { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string DiaChi { get; set; }
        public string QueQuan { get; set; }
        public string MaTonGiao { get; set; }
        public string MaQuocTich { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHP> CTHPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOCPHI> HOCPHIs { get; set; }
        public virtual LOP LOP { get; set; }
        public virtual PHUHUYNH PHUHUYNH { get; set; }
        public virtual QUOCTICH QUOCTICH { get; set; }
        public virtual TONGIAO TONGIAO { get; set; }
    }
}
