//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHocSinhHVT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class HOCSINH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOCSINH()
        {
            this.CTHPs = new HashSet<CTHP>();
            this.HOCPHIs = new HashSet<HOCPHI>();
        }
        [DisplayName("Mã học sinh")]
        public string MaHS { get; set; }
        [DisplayName("Họ học sinh")]
        public string HoHS { get; set; }
        [DisplayName("Tên học sinh")]
        public string TenHS { get; set; }
        [DisplayName("Ảnh học sinh")]
        public string AnhHS { get; set; }
        [DisplayName("Giới tính")]
        public bool GioiTinh { get; set; }
        [DisplayName("Mã lớp học sinh")]
        public string MaLop { get; set; }
        [DisplayName("Mã phụ huynh")]
        public string MaPH { get; set; }
        [DisplayName("Ngày sinh")]
        public System.DateTime NgaySinh { get; set; }
        [DisplayName("Số điện thoại")]
        public string SDT { get; set; }
        [DisplayName("Email")]
        public string Email { get; set; }
        [DisplayName("Địa chỉ")]
        public string DiaChi { get; set; }
        [DisplayName("Quê quán")]
        public string QueQuan { get; set; }
        [DisplayName("Tôn giáo")]
        public string TonGiao { get; set; }
        [DisplayName("Quốc tịch")]
        public string QuocTich { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHP> CTHPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOCPHI> HOCPHIs { get; set; }
        public virtual LOP LOP { get; set; }
        public virtual PHUHUYNH PHUHUYNH { get; set; }
    }
}
