//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KETQUA
    {
        public string MaKQ { get; set; }
        public string MaCTHP { get; set; }
        public double DiemQT { get; set; }
        public double Diem1T { get; set; }
        public double DiemKT { get; set; }
        public double DiemTB { get; set; }
    
        public virtual CTHP CTHP { get; set; }
    }
}
