//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class MONHOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MONHOC()
        {
            this.CTHPs = new HashSet<CTHP>();
        }
        [DisplayName("Môn học")]
        public string MaMH { get; set; }
        [DisplayName("Tên môn học")]
        public string TenMH { get; set; }
        [DisplayName("Ngành")]
        public string MaNganh { get; set; }
        public string MaKhoi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHP> CTHPs { get; set; }
        public virtual KHOI KHOI { get; set; }
        public virtual NGANH NGANH { get; set; }
    }
}
