//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class PHUHUYNH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHUHUYNH()
        {
            this.HOCSINHs = new HashSet<HOCSINH>();
        }
        [DisplayName("Phụ huynh")]
        public string MaPH { get; set; }
        [DisplayName("Họ phụ huynh")]
        public string HoPH { get; set; }
        [DisplayName("Tên phụ huynh")]
        public string TenPH { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        [DisplayName("Nghề nghiệp")]
        public string NgheNghiep { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOCSINH> HOCSINHs { get; set; }
    }
}
