//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class THAMSO
    {
        public string MaThamSo { get; set; }
        [DisplayName("Giá trị tối thiểu")]
        public int GiaTriToiThieu { get; set; }
        [DisplayName("Giá trị tối đa")]
        public int GiaTriToiDa { get; set; }
    }
}
